const { test } = require('@playwright/test');

test('Employer Registration', async ({ page }) => { 
  
  await page.goto('https://www.wyo-platform-pre-prod.careeredgebeta.com/employer-jobseeker/employers/registration');
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('jed');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('Employer');
  await page.getByRole('textbox', { name: 'Email Providing your email' }).click();
  await page.getByRole('textbox', { name: 'Email Providing your email' }).fill('ajregunay+thursday@careerteam.com');
  await page.getByRole('textbox', { name: 'Password Create a secure' }).click();
  await page.getByRole('textbox', { name: 'Password Create a secure' }).fill('Hellohello123!');
  await page.getByRole('textbox', { name: 'Confirm Password *' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).fill('Hellohello123!');
  await page.getByRole('textbox', { name: 'Company Name Enter your' }).click();
  await page.getByRole('textbox', { name: 'Company Name Enter your' }).fill('Jed Test Employer');
  await page.getByRole('textbox', { name: 'Federal Employer Id Number Federal Employer ID Number (EIN)/Federal Tax ID (' }).click();
  await page.getByRole('textbox', { name: 'Federal Employer Id Number Federal Employer ID Number (EIN)/Federal Tax ID (' }).fill('920182934');
  await page.getByRole('textbox', { name: 'Confirm Federal Employer Id' }).click();
  await page.getByRole('textbox', { name: 'Confirm Federal Employer Id' }).fill('920182934');
  await page.getByText('SelectRemove item').first().click();
  await page.getByRole('option', { name: 'Agriculture, Forestry,' }).click();
  await page.getByLabel('data[basicInfo.numberOfEmployees]').getByText('SelectRemove item').click();
  await page.getByRole('option', { name: '5-' }).click();
  await page.getByText('SelectRemove item').click();
  await page.getByText('Federal Government').click();
  await page.getByRole('radio', { name: 'No. I am not a Federal' }).check();
  await page.getByRole('radio', { name: 'Yes', exact: true }).check();
  await page.getByRole('radio', { name: 'No benefits provided' }).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).click();
  await page.getByRole('textbox', { name: 'Location Name' }).fill('Test');
  await page.getByRole('group', { name: 'Primary Location' }).getByLabel('Address Line 1').click();
  await page.getByRole('group', { name: 'Primary Location' }).getByLabel('Address Line 1').fill('test');
  await page.getByRole('group', { name: 'Primary Location' }).getByLabel('City').click();
  await page.getByRole('group', { name: 'Primary Location' }).getByLabel('City').fill('Buffalo');
  await page.getByText('SelectRemove item').first().click();
  await page.getByRole('textbox', { name: 'Select' }).fill('wyoming');
  await page.getByText('Wyoming').click();
  await page.getByRole('group', { name: 'Primary Location' }).getByLabel('Zip Code').click();
  await page.getByRole('group', { name: 'Primary Location' }).getByLabel('Zip Code').fill('82834');
  await page.getByRole('checkbox', { name: 'Check here if Mailing' }).check();
  await page.getByRole('textbox', { name: 'Job Title Employer should' }).click();
  await page.getByRole('textbox', { name: 'Job Title Employer should' }).fill('Tubero');
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Mark');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('Imperial');
  await page.getByRole('textbox', { name: 'Mobile Number , numeric only' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number , numeric only' }).fill('9154564836');
  await page.getByRole('textbox', { name: 'Work Phone Number , numeric' }).click();
  await page.getByRole('textbox', { name: 'Work Phone Number , numeric' }).fill('9154564836');
  await page.getByRole('textbox', { name: 'Email *' }).click();
  await page.getByRole('textbox', { name: 'Email *' }).fill('markielimperial_pwtestemployer@careerteam.com');
  await page.getByRole('checkbox', { name: 'Email' }).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.pause();
});