import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.wyo-platform-pre-prod.careeredgebeta.com/employer-jobseeker/job-seeker/registration');
  await page.getByRole('textbox', { name: 'First Name *' }).click();
  await page.getByRole('textbox', { name: 'First Name *' }).fill('Twe');
  await page.getByRole('textbox', { name: 'Last Name *' }).click();
  await page.getByRole('textbox', { name: 'Last Name *' }).fill('Coel');
  await page.getByRole('textbox', { name: 'Email You may be contacted' }).click();
  await page.getByRole('textbox', { name: 'Email You may be contacted' }).fill('coeltwe@careerteam.com');
  await page.getByRole('textbox', { name: 'Password Create a secure' }).click();
  await page.getByRole('textbox', { name: 'Password Create a secure' }).fill('High_hello123!');
  await page.getByRole('textbox', { name: 'Confirm Password *' }).click();
  await page.getByRole('textbox', { name: 'Confirm Password *' }).fill('High_hello123!');
  await page.getByRole('textbox', { name: 'Social Security Number (SSN) Enter your Social Security Number without using' }).click();
  await page.getByRole('textbox', { name: 'Social Security Number (SSN) Enter your Social Security Number without using' }).fill('667334155');
  await page.getByRole('textbox', { name: 'Confirm Social Security' }).click();
  await page.getByRole('textbox', { name: 'Confirm Social Security' }).fill('667334155');
  await page.getByRole('textbox', { name: 'Zip Code Enter the Zip Code' }).click();
  await page.getByRole('textbox', { name: 'Zip Code Enter the Zip Code' }).fill('82001');
  await page.getByRole('textbox', { name: 'Date of Birth Select your' }).click();
  await page.getByRole('textbox', { name: 'Date of Birth Select your' }).fill('07/01/2006_');
  await page.getByText('Select GenderSelect').click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.getByText('Select Sexual OrientationSelect Sexual OrientationRemove item').click();
  await page.getByRole('option', { name: 'Straight/Heterosexual' }).click();
  await page.getByLabel('data[basicInfo.isSelectiveService]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'No', exact: true }).click();
  await page.getByLabel('data[basicInfo.siteAccessingFrom]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'Elementary School' }).click();
  await page.getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'Magazine Ad' }).click();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('radiogroup', { name: 'Are you homeless? Are you' }).getByLabel('No').check();
  await page.getByRole('textbox', { name: 'Address Line 1 Enter your' }).click();
  await page.getByRole('textbox', { name: 'Address Line 1 Enter your' }).fill('Test');
  await page.getByRole('textbox', { name: 'City *' }).click();
  await page.getByRole('textbox', { name: 'City *' }).fill('test');
  await page.getByText('StateStateRemove item').click();
  await page.getByRole('textbox', { name: 'State' }).fill('wy');
  await page.getByRole('option', { name: 'Wyoming' }).click();
  await page.getByRole('textbox', { name: 'Primary Phone Number ,' }).click();
  await page.getByRole('textbox', { name: 'Primary Phone Number ,' }).fill('(565) 343-4342_');
  await page.getByRole('radio', { name: 'Message Only' }).check();
  await page.getByRole('checkbox', { name: 'Email' }).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'Citizen of U.S. or U.S.' }).click();
  await page.getByRole('radio', { name: 'No, I do not have a' }).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByLabel('data[eduInfo.highestEduAchieved]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'No Educational Level Completed' }).click();
  await page.getByLabel('data[eduInfo.areYouAttendingSchool]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'Yes, Attending An Alternative' }).click();
  await page.getByLabel('data[eduInfo.currentEmploymentStatus]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'Not in labor force' }).click();
  await page.getByLabel('data[eduInfo.unEmpEligibilityStatus]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: 'Neither Claimant nor Exhaustee' }).click();
  await page.getByRole('radiogroup', { name: 'Are you currently looking for' }).getByLabel('No').check();
  await page.getByRole('radiogroup', { name: 'Do you have any related' }).getByLabel('No').check();
  await page.getByRole('radio', { name: 'No, I have not recently' }).check();
  await page.getByRole('radiogroup', { name: 'Have you worked as a' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('radiogroup', { name: 'Are you of Hispanic or Latino' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('checkbox', { name: 'African American/Black' }).check();
  await page.getByRole('radiogroup', { name: 'Do you primarily speak a' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'Are you currently in the U.S' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'I am the spouse or family' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'My spouse was a veteran who' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'My spouse has (or my deceased' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radio', { name: 'None of the above' }).check();
  await page.getByPlaceholder('Would you like to be').nth(1).check();
  await page.getByRole('button', { name: 'Submit Form button. Click to' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.goto('https://www.wyo-platform-dev.careeredgebeta.com/home');
});