import { test, expect } from '@playwright/test';

test('WP Application', async ({ page }) => {
  await page.goto('https://www.wyo-platform-dev.careeredgebeta.com/user/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ajregunay+wyo@careerteam.com');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('kec5mtv_uae9gbz_RYG');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.goto('https://www.wyo-platform-dev.careeredgebeta.com/home');
  await page.getByRole('button', { name: 'Individuals' }).click();
  await page.goto('https://www.wyo-platform-dev.careeredgebeta.com/employer-jobseeker/individuals?tab=allIndividuals');
  await page.getByLabel('power').click();
  await page.getByText('Wagner Peyser').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByLabel('In a Registered').getByText('No', { exact: true }).click();
  await page.getByText('Neither Claimant nor Exhaustee').click();
  await page.getByRole('radiogroup', { name: 'Unemployed due to layoff or' }).getByLabel('No').check();
  await page.getByRole('radiogroup', { name: 'Long-Term Unemployed *' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'Attended a Rapid Response' }).getByLabel('No', { exact: true }).check();
  await page.getByLabel('data[').getByText('SelectRemove item').click();
  await page.getByRole('option', { name: 'Migrant Farmworker Adult' }).click();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByLabel('data[highestSchoolGradeCompleted]').getByText('SelectSelectRemove item').click();
  await page.getByRole('option', { name: '12th Grade Completed' }).click();
  await page.getByLabel('data[highestEducationalLevelCompleted]').getByText('SelectRemove item').click();
  await page.getByText('High School Equivalency').click();
  await page.getByText('SelectRemove item').click();
  await page.getByRole('option', { name: 'Yes, Attending An Alternative' }).click();
  await page.getByRole('radiogroup', { name: 'Receiving services from Adult' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'Receiving services from YouthBuild *' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'Receiving services from Job' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'Receiving services from Vocational Education (Carl Perkins) *' }).getByLabel('No', { exact: true }).check();
  await page.getByRole('radiogroup', { name: 'Temporary Assistance for' }).getByLabel('No', { exact: true }).check();
  await page.locator('#elftuwc > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.locator('input[name="data[generalAssistance][es7k4aa-etzw0nv]"]').nth(1).check();
  await page.locator('#e19r8i > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.locator('input[name="data[refugeeCashAssistance][es7k4aa-e7fr64]"]').nth(1).check();
  await page.locator('input[name="data[socialSecurityDisabilityInsuranceSsdiRecipient][es7k4aa-e5z74v]"]').nth(1).check();
  await page.locator('input[name="data[highPovertyArea][es7k4aa-e6van1r]"]').nth(1).check();
  await page.locator('input[name="data[fosterCarePayments][es7k4aa-ef7yq2a]"]').nth(1).check();
  await page.locator('input[name="data[youthCurrentlyReceivesOrIsEligibleToReceiveFreeOrReducedLunchUnderTheRichardBRussellNationalSchoolLunchAct][es7k4aa-ekj847d]"]').nth(1).check();
  await page.locator('#ew6k64rs > .form-radio > div:nth-child(2) > .form-check-label').click();
  await page.locator('input[name="data[ticketToWorkHolderIssuedBySocialSecurityAdministration][es7k4aa-ekqu5w8]"]').nth(1).check();
  await page.locator('input[name="data[theTicketToWorkHasBeenAssignedAnEmploymentNetwork][es7k4aa-eepwzq]"]').nth(1).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('radiogroup', { name: 'English Language Learner *' }).getByLabel('No').check();
  await page.getByRole('radiogroup', { name: 'Basic Skills Deficient/Low' }).getByLabel('No').check();
  await page.getByRole('radiogroup', { name: 'Runaway *' }).getByLabel('No').check();
  await page.getByRole('radiogroup', { name: 'Foster Care Status *' }).getByLabel('No').check();
  await page.getByRole('radiogroup', { name: 'Ex-Offender *' }).getByLabel('No', { exact: true }).check();
  await page.locator('input[name="data[singleParentIncludingSinglePregnantWomen][es7k4aa-e1t58w9]"]').nth(1).check();
  await page.locator('input[name="data[within2YearsOfExhaustingTanfLifetimeEligibility][es7k4aa-e4tp532]"]').nth(1).check();
  await page.locator('input[name="data[displacedHomemaker][es7k4aa-ewie7bq]"]').nth(1).check();
  await page.locator('input[name="data[culturalBarriers][es7k4aa-e6j5aft]"]').nth(1).check();
  await page.locator('input[name="data[areYouRequiredToPayChildSupport][es7k4aa-ei3y8ek]"]').nth(1).check();
  await page.getByRole('button', { name: 'Next button. Click to go to' }).click();
  await page.getByRole('button', { name: 'Submit button. Click to' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
});